---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repository
      apt:
        update_cache: yes
      change_when: Fales

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
