---

- hosts: localhost
  connection: local
  become: true

  vars:
      ansible_shell_allow_world_readable_temp: true 
      ssh_users: "john"

  tasks:
    - include: tasks/dotfiles.yml
    - include: tasks/rootdotfiles.yml
    - include: tasks/localbin.yml
    - include: tasks/rootbin.yml

  handlers:
    - name: restart_sshd
      service:
        name: sshd
        state: restarted
    - name: update_grub
      shell:
        cmd: update-grub
