- name: add ansible user
  user:
    name: ansible
    system: yes

- name: copy sudoers_john
  tags: sudo,settings,users,base
  copy:
    src: files/etc/sudoers.d/sudoers_john
    dest: /etc/sudoers.d/john
    owner: root
    group: root
    mode: 0440

- name: copy sudoers_ansible
  tags: sudo,settings,users,base
  copy:
    src: files/etc/sudoers.d/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
