- name: configure ~/.themes directory for dwa
  tags: themes,settings,users,desktop
  file:
      path: /home/dwa/.themes
      state: directory
      owner: dwa
      group: dwa

- name: install the Nordic theme for dwa
  tags: themes,settings,users,desktop
  ansible.builtin.git:
    repo: https://github.com/EliverLara/Nordic.git
    dest: /home/dwa/.themes/Nordic
  become_user: dwa

- name: install the Nord-Openbox theme for dwa
  tags: themes,settings,users,desktop
  ansible.builtin.git:
    repo: https://gitlab.com/the-zero885/nord-openbox-theme.git
    dest: /home/dwa/.themes/nord-openbox
  become_user: dwa

- name: configure environment
  tags: themes,settings,desktop
  template:
    src: files/etc/environment
    dest: /etc/environment
    owner: root
    group: root
    mode: 0644
