- name: configure ~/.themes directory for john
  tags: themes,settings,users,desktop
  file:
      path: /home/john/.themes
      state: directory
      owner: john
      group: john

- name: install the Nordic theme for john
  tags: themes,settings,users,desktop
  ansible.builtin.git:
    repo: https://github.com/EliverLara/Nordic.git
    dest: /home/john/.themes/Nordic
  become_user: john

- name: install the Nord-Openbox theme for john
  tags: themes,settings,users,desktop
  ansible.builtin.git:
    repo: https://gitlab.com/the-zero885/nord-openbox-theme.git
    dest: /home/john/.themes/nord-openbox
  become_user: john

- name: configure environment
  tags: themes,settings,desktop
  template:
    src: files/etc/environment
    dest: /etc/environment
    owner: root
    group: root
    mode: 0644
