---
- name: Copy .bashrc for user home dir
  copy:
    src: files/.bashrc
    dest: /root/.bashrc
    owner: root
    group: root
    mode: 0664
    backup: yes
- name: Copy .bash_aliases for user home dir
  copy:
    src: files/.bash_aliases
    dest: /root/.bash_aliases
    owner: root
    group: root
    mode: 0664
    backup: yes
- name: Copy .tmux.conf for user home dir
  copy:
    src: files/.tmux.conf
    dest: /root/.tmux.conf
    owner: root
    group: root
    mode: 0664
    backup: yes
- name: Copy .vimrc for user home dir
  copy:
    src: files/.vimrc
    dest: /root/.vimrc
    owner: root
    group: root
    mode: 0664
    backup: yes
